#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --job-name=Train_SASRec
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --mem=32000M
#SBATCH --output=logs/train/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2
# module load CUDA/12.4.0

# Activate your environment
source activate sasrec_torch

# Run your code
srun python main.py --dataset=Beauty --train_dir=default --maxlen=200 --dropout_rate=0.2 --device=cuda