#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=train_amazon
#SBATCH --time=12:00:00
#SBATCH --output=./slurm_output/train/amazon_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0

source activate rq-vae

# train rq-vae
python train_rqvae.py configs/rqvae_amazon.gin

# train decoder
# python train_decoder.py configs/decoder_amazon.gin